### PR TITLE
support both arm64 and amd64 images

### PR DESCRIPTION
**Pull request by James-Mart**

### CODE REVIEW

**Comment by James-Mart** [comment]
When building psibase in amd64 environment based on the multi-arch image, I still get the following error:
```
ccache /opt/clang+llvm-14.0.0/bin/clang --sysroot=/opt/clang+llvm-14.0.0/share/wasi-sysroot --target=wasm32-wasi -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example example.o -target wasm32-wasi -L. libz.a
ccache /opt/clang+llvm-14.0.0/bin/clang --sysroot=/opt/clang+llvm-14.0.0/share/wasi-sysroot --target=wasm32-wasi -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip minigzip.o -target wasm32-wasi -L. libz.a
ccache /opt/clang+llvm-14.0.0/bin/clang --sysroot=/opt/clang+llvm-14.0.0/share/wasi-sysroot --target=wasm32-wasi -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example64 example64.o -target wasm32-wasi -L. libz.a
ccache /opt/clang+llvm-14.0.0/bin/clang --sysroot=/opt/clang+llvm-14.0.0/share/wasi-sysroot --target=wasm32-wasi -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip64 minigzip64.o -target wasm32-wasi -L. libz.a
wasm-ld: error: /opt/clang+llvm-14.0.0/share/wasi-sysroot/lib/wasm32-wasi/libc.a(__main_void.o): undefined symbol: main
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
wasm-ld: error: /opt/clang+llvm-14.0.0/share/wasi-sysroot/lib/wasm32-wasi/libc.a(__main_void.o): undefined symbol: main
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Makefile:285: example] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:300: minigzip64] Error 1
wasm-ld: error: /opt/clang+llvm-14.0.0/share/wasi-sysroot/lib/wasm32-wasi/libc.a(__main_void.o): undefined symbol: main
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Makefile:297: example64] Error 1
wasm-ld: error: /opt/clang+llvm-14.0.0/share/wasi-sysroot/lib/wasm32-wasi/libc.a(__main_void.o): undefined symbol: main
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Makefile:288: minigzip] Error 1
make[4]: Leaving directory '/root/psibase/build/wasm/deps/zlib-1.2.13'
```

Attached is the log that shows the rest of the context for that error.
[build.log](https://github.com/gofractally/image-builders/files/11807498/build.log)

Interestingly, psibase seems to have built @swatanabe?

**Comment by swatanabe** [comment]
IIRC, zlib is needed because openssl depends on it, but we're not actually using any of those parts of openssl. We might be able to get away without it now.

**Comment by swatanabe** [comment]
I can reproduce the error by using an older version of clang with wasi-sdk-19.

**Comment by swatanabe** [comment]
It should be fixed by updating clang

**Comment by James-Mart** [comment]
> It should be fixed by updating clang

Updated clang, can confirm it was fixed. Whole build seems to have been succesful.

**Pull request merged**
